// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230602143927_Init1")]
    partial class Init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataLayer.Entityes.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("DataLayer.Entityes.Airline_Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdAirline")
                        .HasColumnType("int");

                    b.Property<int>("IdRoute")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAirline");

                    b.HasIndex("IdRoute");

                    b.ToTable("Airline_Routes");
                });

            modelBuilder.Entity("DataLayer.Entityes.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfManufacture")
                        .HasColumnType("date");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("DataLayer.Entityes.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdCity");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("DataLayer.Entityes.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTicket");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("DataLayer.Entityes.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DataLayer.Entityes.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDepature")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfDestination")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdAirplane")
                        .HasColumnType("int");

                    b.Property<int>("IdRoute")
                        .HasColumnType("int");

                    b.Property<int>("freePlaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAirplane");

                    b.HasIndex("IdRoute");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("DataLayer.Entityes.Klass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Klasses");
                });

            modelBuilder.Entity("DataLayer.Entityes.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DataLayer.Entityes.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("FlightDuration")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdAirportOfDepature")
                        .HasColumnType("int");

                    b.Property<int>("IdAirportOfDestination")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAirportOfDepature");

                    b.HasIndex("IdAirportOfDestination");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("DataLayer.Entityes.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdFlight")
                        .HasColumnType("int");

                    b.Property<string>("LoginUser")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Seat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdFlight");

                    b.HasIndex("LoginUser");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("DataLayer.Entityes.User", b =>
                {
                    b.Property<string>("LoginUser")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passport")
                        .HasColumnType("longtext");

                    b.HasKey("LoginUser");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataLayer.Entityes.Airline_Route", b =>
                {
                    b.HasOne("DataLayer.Entityes.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("IdAirline")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entityes.Route", "Route")
                        .WithMany()
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("DataLayer.Entityes.Airport", b =>
                {
                    b.HasOne("DataLayer.Entityes.City", "City")
                        .WithMany()
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DataLayer.Entityes.Booking", b =>
                {
                    b.HasOne("DataLayer.Entityes.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DataLayer.Entityes.Flight", b =>
                {
                    b.HasOne("DataLayer.Entityes.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("IdAirplane")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entityes.Route", "Route")
                        .WithMany()
                        .HasForeignKey("IdRoute")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("DataLayer.Entityes.Route", b =>
                {
                    b.HasOne("DataLayer.Entityes.Airport", "AirportOfDepature")
                        .WithMany()
                        .HasForeignKey("IdAirportOfDepature")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entityes.Airport", "AirportOfDestination")
                        .WithMany()
                        .HasForeignKey("IdAirportOfDestination")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirportOfDepature");

                    b.Navigation("AirportOfDestination");
                });

            modelBuilder.Entity("DataLayer.Entityes.Ticket", b =>
                {
                    b.HasOne("DataLayer.Entityes.Klass", "Class")
                        .WithMany()
                        .HasForeignKey("IdClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entityes.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("IdFlight")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Entityes.User", "User")
                        .WithMany()
                        .HasForeignKey("LoginUser");

                    b.Navigation("Class");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataLayer.Entityes.User", b =>
                {
                    b.HasOne("DataLayer.Entityes.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
